name: AI Code Reviewer

on:
  pull_request:
    types:
      - opened
      - synchronize

permissions: write-all

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: AI Code Reviewer
        uses: AleksandrFurmenkovOfficial/ai-code-review@v0.8
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          owner: ${{ github.repository_owner }}
          repo: ${{ github.event.repository.name }}
          pr_number: ${{ github.event.number }}
          ai_provider: 'google'
          google_api_key: ${{ secrets.GOOGLE_API_KEY }}
          google_model: 'gemini-2.5-flash'
          exclude_extensions: "json,md"